-- Texas candidate lookup — PostgreSQL schema

CREATE TABLE IF NOT EXISTS offices (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category TEXT NOT NULL CHECK (category IN ('house', 'senate', 'sboe', 'statewide', 'congressional')),
  district INTEGER,
  office_code TEXT NOT NULL UNIQUE,
  office_name TEXT NOT NULL,
  sort_order INTEGER NOT NULL DEFAULT 0,
  seat_holder_name TEXT,
  seat_holder_party TEXT CHECK (seat_holder_party IS NULL OR seat_holder_party IN ('R', 'D', 'I', 'L', 'G', 'O')),
  up_for_reelection INTEGER NOT NULL DEFAULT 0 CHECK (up_for_reelection IN (0, 1)),
  county_name TEXT
);

CREATE INDEX IF NOT EXISTS idx_offices_category_sort ON offices(category, sort_order, district);

CREATE TABLE IF NOT EXISTS candidates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
  cycle_year INTEGER NOT NULL,
  party TEXT NOT NULL CHECK (party IN ('R', 'D', 'I', 'L', 'G', 'O')),
  name TEXT NOT NULL DEFAULT '',
  is_incumbent INTEGER NOT NULL DEFAULT 0 CHECK (is_incumbent IN (0, 1)),
  withdrew INTEGER NOT NULL DEFAULT 0 CHECK (withdrew IN (0, 1)),
  filed INTEGER NOT NULL DEFAULT 0 CHECK (filed IN (0, 1)),
  running_for_reelection TEXT,
  tec_filer_id TEXT,
  consultant TEXT,
  endorsements TEXT,
  notes TEXT,
  website TEXT,
  social_media TEXT,
  race_category TEXT,
  vuid TEXT
);

CREATE INDEX IF NOT EXISTS idx_candidates_office_cycle ON candidates(office_id, cycle_year);
CREATE INDEX IF NOT EXISTS idx_candidates_lookup ON candidates(office_id, cycle_year, party, name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_candidates_vuid ON candidates(vuid) WHERE vuid IS NOT NULL AND vuid != '';

CREATE TABLE IF NOT EXISTS election_results (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
  cycle_year INTEGER NOT NULL,
  election_type TEXT NOT NULL CHECK (election_type IN ('primary', 'runoff', 'general')),
  candidate_id INTEGER REFERENCES candidates(id) ON DELETE SET NULL,
  candidate_name TEXT NOT NULL,
  party TEXT NOT NULL,
  votes INTEGER,
  vote_pct DOUBLE PRECISION,
  won INTEGER NOT NULL DEFAULT 0 CHECK (won IN (0, 1)),
  source TEXT,
  UNIQUE (office_id, cycle_year, election_type, party, candidate_name)
);

CREATE INDEX IF NOT EXISTS idx_results_office_cycle ON election_results(office_id, cycle_year);

CREATE TABLE IF NOT EXISTS filing_periods (
  period_key TEXT PRIMARY KEY,
  label TEXT NOT NULL,
  sort_order INTEGER NOT NULL,
  default_report_period_end TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_filing_periods_label ON filing_periods (LOWER(label));
CREATE INDEX IF NOT EXISTS idx_filing_periods_sort ON filing_periods(sort_order);

CREATE TABLE IF NOT EXISTS finance_reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id INTEGER NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  period_key TEXT REFERENCES filing_periods(period_key),
  report_period_end TEXT NOT NULL,
  report_type TEXT NOT NULL DEFAULT 'TEC',
  total_raised DOUBLE PRECISION,
  total_spent DOUBLE PRECISION,
  cash_on_hand DOUBLE PRECISION,
  debt DOUBLE PRECISION,
  filed_at TEXT,
  source_url TEXT,
  UNIQUE (candidate_id, report_period_end, report_type)
);

CREATE INDEX IF NOT EXISTS idx_finance_candidate ON finance_reports(candidate_id);

CREATE TABLE IF NOT EXISTS race_sheet_rows (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
  cycle_year INTEGER NOT NULL,
  category TEXT NOT NULL,
  row_order INTEGER NOT NULL,
  incumbent_name TEXT NOT NULL DEFAULT '',
  incumbent_party TEXT,
  running_for_reelection TEXT,
  candidate_name TEXT NOT NULL DEFAULT '',
  candidate_party TEXT,
  filed INTEGER NOT NULL DEFAULT 0 CHECK (filed IN (0, 1)),
  tec_filer_id TEXT,
  consultant TEXT,
  endorsements TEXT,
  notes TEXT,
  social_media TEXT,
  website TEXT,
  race_category TEXT
);

CREATE INDEX IF NOT EXISTS idx_sheet_rows_category ON race_sheet_rows(category, cycle_year, row_order);

CREATE TABLE IF NOT EXISTS office_metrics (
  office_id INTEGER PRIMARY KEY REFERENCES offices(id) ON DELETE CASCADE,
  trump_2024 DOUBLE PRECISION,
  cruz_2024 DOUBLE PRECISION,
  abbott_2022 DOUBLE PRECISION,
  leg_2024 DOUBLE PRECISION,
  leg_2022 DOUBLE PRECISION
);

CREATE TABLE IF NOT EXISTS county_election_results (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  election_key TEXT NOT NULL CHECK (election_key IN ('pres_2024', 'cruz_2024', 'abbott_2022')),
  county_name TEXT NOT NULL,
  county_key TEXT NOT NULL,
  margin DOUBLE PRECISION,
  gop_pct DOUBLE PRECISION,
  dem_pct DOUBLE PRECISION,
  gop_votes INTEGER,
  dem_votes INTEGER,
  UNIQUE (election_key, county_key)
);

CREATE INDEX IF NOT EXISTS idx_county_election ON county_election_results(election_key, county_key);

CREATE TABLE IF NOT EXISTS metric_contest_candidates (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
  metric_key TEXT NOT NULL,
  candidate_name TEXT NOT NULL,
  party TEXT NOT NULL,
  votes INTEGER,
  vote_pct DOUBLE PRECISION,
  contest_margin DOUBLE PRECISION,
  sort_order INTEGER NOT NULL DEFAULT 0,
  unopposed INTEGER NOT NULL DEFAULT 0 CHECK (unopposed IN (0, 1)),
  contest_name TEXT,
  source TEXT,
  UNIQUE (office_id, metric_key, candidate_name, party)
);

CREATE INDEX IF NOT EXISTS idx_metric_contest_lookup ON metric_contest_candidates(office_id, metric_key);

CREATE TABLE IF NOT EXISTS candidate_coh_history (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
  cycle_year INTEGER NOT NULL,
  candidate_name TEXT NOT NULL,
  party TEXT NOT NULL,
  is_incumbent INTEGER NOT NULL DEFAULT 0 CHECK (is_incumbent IN (0, 1)),
  period_label TEXT NOT NULL,
  report_period_end TEXT,
  cash_on_hand DOUBLE PRECISION NOT NULL,
  UNIQUE (office_id, cycle_year, candidate_name, party, is_incumbent, period_label)
);

CREATE INDEX IF NOT EXISTS idx_coh_history_lookup
  ON candidate_coh_history(office_id, cycle_year, candidate_name, party, is_incumbent);

CREATE TABLE IF NOT EXISTS targeting_organizations (
  org_key TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_targeting_organizations_name ON targeting_organizations (LOWER(name));

CREATE TABLE IF NOT EXISTS office_targets (
  office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
  cycle_year INTEGER NOT NULL,
  org_key TEXT NOT NULL REFERENCES targeting_organizations(org_key) ON DELETE CASCADE,
  PRIMARY KEY (office_id, cycle_year, org_key)
);

CREATE INDEX IF NOT EXISTS idx_office_targets_office_cycle ON office_targets(office_id, cycle_year);
CREATE INDEX IF NOT EXISTS idx_office_targets_org ON office_targets(org_key);

CREATE TABLE IF NOT EXISTS consultants (
  consultant_key TEXT PRIMARY KEY,
  name TEXT NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_consultants_name ON consultants (LOWER(name));

CREATE TABLE IF NOT EXISTS candidate_consultants (
  candidate_id INTEGER NOT NULL REFERENCES candidates(id) ON DELETE CASCADE,
  consultant_key TEXT NOT NULL REFERENCES consultants(consultant_key) ON DELETE CASCADE,
  PRIMARY KEY (candidate_id, consultant_key)
);

CREATE INDEX IF NOT EXISTS idx_candidate_consultants_candidate ON candidate_consultants(candidate_id);

CREATE TABLE IF NOT EXISTS tga_staffers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  office_id INTEGER REFERENCES offices(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_tga_staffers_office ON tga_staffers(office_id);

CREATE TABLE IF NOT EXISTS tga_staffer_offices (
  staffer_id INTEGER NOT NULL REFERENCES tga_staffers(id) ON DELETE CASCADE,
  office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
  PRIMARY KEY (staffer_id, office_id)
);

CREATE INDEX IF NOT EXISTS idx_tga_staffer_offices_office ON tga_staffer_offices(office_id);

CREATE TABLE IF NOT EXISTS tga_staffer_counties (
  staffer_id INTEGER NOT NULL REFERENCES tga_staffers(id) ON DELETE CASCADE,
  county_name TEXT NOT NULL,
  PRIMARY KEY (staffer_id, county_name)
);

CREATE TABLE IF NOT EXISTS office_counties (
  office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
  county_name TEXT NOT NULL,
  PRIMARY KEY (office_id, county_name)
);

CREATE INDEX IF NOT EXISTS idx_office_counties_county ON office_counties(county_name);

CREATE TABLE IF NOT EXISTS app_users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('admin', 'viewer')) DEFAULT 'viewer',
  password_hash TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_users_role ON app_users(role);

CREATE TABLE IF NOT EXISTS app_sessions (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
  token_hash TEXT NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  remember_me INTEGER NOT NULL DEFAULT 0 CHECK (remember_me IN (0, 1)),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_sessions_user ON app_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_app_sessions_expires ON app_sessions(expires_at);

CREATE TABLE IF NOT EXISTS app_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);
