"""Initial historical dataset for Texas Governor 2026, after the late-May primaries.

Every figure below is tied to a source note. Aggregator-only figures are stored
and kept out of the model until a primary release confirms them.

Retrieved and checked on 2026-10-02. This is not a claim that later revisions
do not exist; the change detector is supposed to catch those.
"""

from __future__ import annotations


def _pair(labels, abbott, hinojosa, dimension, definition=None):
    rows = []
    for label, a, b in zip(labels, abbott, hinojosa):
        for candidate, party, pct in (
            ("Greg Abbott", "Republican", a),
            ("Gina Hinojosa", "Democrat", b),
        ):
            rows.append(
                {
                    "dimension": dimension,
                    "subgroup": label,
                    "candidate": candidate,
                    "party": party,
                    "percentage": pct,
                    "subgroup_n": None,
                    "definition": definition,
                    "notes": "Subgroup sample size not reported.",
                }
            )
    return rows


def historical_polls() -> list[dict]:
    # Likely-voter crosstab. The party block has no Independent column.
    # Ideology is Lib / Mod / Cons, not the urban cells beside them.
    # College degree: Abbott 49, Hinojosa 50. No degree: Abbott 55, Hinojosa 45.
    fox_groups = [
        ("gender", ["Men", "Women"], [54, 50], [45, 49]),
        ("race_ethnicity", ["White", "Hispanic", "Black Voters"], [62, 34, 26], [37, 65, 73]),
        ("age", ["Under Age 35", "Age 65+"], [38, 58], [62, 41]),
        ("party", ["Dem", "GOP"], [5, 92], [95, 7]),
        ("ideology", ["Lib", "Mod", "Cons"], [11, 40, 84], [89, 59, 15]),
        ("urbanicity", ["Urban", "Sub urban", "Rural"], [44, 54, 61], [55, 46, 38]),
        ("vote_history", ["2024 Trump Voters", "2024 Harris Voters"], [90, 4], [10, 95]),
        ("education", ["College Degree", "No Degree"], [49, 55], [50, 45]),
    ]
    fox_subgroups = []
    for dimension, labels, abbott, hinojosa in fox_groups:
        fox_subgroups.extend(
            _pair(
                labels,
                abbott,
                hinojosa,
                dimension,
                "Fox September 24–28, 2026 likely-voter crosstab. Exact subgroup n is not printed. Fox shows a subgroup only when n is at least 100.",
            )
        )

    bush_subgroups = []
    bush_map = [
        ("party", "DEM", 2, 95),
        ("party", "REP", 92, 3),
        ("party", "IND/OTHER", 36, 49),
        ("age", "18-34", 23, 65),
        ("age", "35-49", 33, 52),
        ("age", "50-64", 47, 46),
        ("age", "65+", 57, 37),
        ("gender", "Male", 51, 38),
        ("gender", "Female", 41, 51),
        ("education", "No Degree", 51, 40),
        ("education", "Bachelors+", 39, 52),
        ("region", "Austin", 27, 68),
        ("region", "DFW", 40, 49),
        ("region", "Houston", 46, 45),
        ("region", "Rural", 56, 33),
        ("region", "San Antonio/South", 45, 48),
        ("race_ethnicity", "White NH", 53, 38),
        ("race_ethnicity", "Black NH", 8, 79),
        ("race_ethnicity", "Hispanic", 42, 53),
    ]
    for dimension, label, abbott, hinojosa in bush_map:
        bush_subgroups.extend(
            _pair(
                [label],
                [abbott],
                [hinojosa],
                dimension,
                "Texas Pulse / Bush School / ReconMR crosstab, July 27–30, 2026. Cell sample sizes are not in the percentage row.",
            )
        )

    return [
        _poll(
            external_key="fox-2026-09",
            pollster="Fox News (Beacon Research / Shaw & Company Research)",
            canonical="Fox News",
            parent="Fox News",
            sponsor="Fox News",
            sponsor_type="media",
            release="2026-10-01",
            start="2026-09-24",
            end="2026-09-28",
            n=881,
            n_note="Likely-voter subsample. The full registered-voter sample is 1,203 and is stored as an alternate frame, not a second poll.",
            sample_type="LV",
            mode=["live telephone", "text-to-web"],
            moe=3.0,
            moe_kind="sampling_error",
            ballot="two_candidate_undecided_permitted",
            flags=["undecided_permitted", "named_candidates_abbott_hinojosa"],
            wording="If the Texas election for governor were today, would you vote for:",
            population="Texas likely voters, defined by Fox from a probabilistic model on a registered-voter file.",
            weighting="Age, race, education, and area, using the American Community Survey, Fox News Voter Analysis, and the voter file.",
            approved=True,
            confidence=0.9,
            results=[
                ("Greg Abbott", "Republican", 52, "candidate"),
                ("Gina Hinojosa", "Democrat", 47, "candidate"),
                ("Don't know", None, 1, "undecided"),
            ],
            alternate=[
                {
                    "sample_type": "RV",
                    "sample_size": 1203,
                    "reported_moe": 2.5,
                    "results": [
                        {"candidate": "Greg Abbott", "percentage": 50},
                        {"candidate": "Gina Hinojosa", "percentage": 49},
                        {"candidate": "Don't know", "percentage": 1},
                    ],
                    "notes": "Registered-voter topline from the same survey. Not entered as a separate model observation.",
                }
            ],
            warnings=[
                "TPP tracker prints Other as n/a and leaves the spread cell blank. The crosstab PDF prints Abbott 52, Hinojosa 47, don't know 1 among likely voters.",
            ],
            sources=[
                _src(1, "crosstab", "https://static.foxnews.com/foxnews.com/content/uploads/2026/10/fox_september-24-28-2026_texas_cross-tabs_october-1-release.pdf", "Fox News", "2026-10-01", True, "Likely-voter and registered-voter crosstabs."),
                _src(1, "news_release", "https://www.foxnews.com/politics/fox-news-poll-its-lone-star-senate-showdown-between-talarico-paxton", "Fox News", "2026-10-01", False, "Article states the 52–47 governor result and the 1,203 / 881 sample split."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Discovery index."),
            ],
            methodology="Live interviewers on landline and cellphone, plus text-to-web. Likely voters are a modeled subsample of registered voters.",
            subgroups=fox_subgroups,
            notes="Joint direction of Beacon Research (D) and Shaw & Company Research (R). Fieldwork contact counts on the registered-voter sample: landline 127, cellphone 789, text-to-web 287.",
        ),
        _poll(
            external_key="tpor-2026-09",
            pollster="Texas Public Opinion Research",
            canonical="Texas Public Opinion Research",
            sponsor="Texas Public Opinion Research",
            sponsor_type="nonpartisan_public",
            release="2026-09-25",
            start="2026-09-19",
            end="2026-09-22",
            n=1007,
            n_note="Stated in the TPOR release.",
            sample_type="LV",
            mode=["unknown"],
            moe=3.6,
            moe_kind="sampling_error",
            ballot="three_candidate_undecided_permitted",
            flags=["three_candidate", "undecided_permitted", "leaners_included"],
            wording=None,
            population="Likely Texas general-election voters.",
            approved=True,
            confidence=0.72,
            results=[
                ("Greg Abbott", "Republican", 50, "candidate"),
                ("Gina Hinojosa", "Democrat", 46, "candidate"),
                ("Pat Dixon", "Libertarian", 2, "candidate"),
                ("Undecided", None, 2, "undecided"),
            ],
            warnings=[
                "TPOR says it is nonpartisan. That is their description; this import does not independently audit the organization.",
                "The release says topline results include leaners. Question wording and mode were not in the narrative. Crosstabs were offered on request and were not published with the article.",
                "Not listed on the Texas Politics Project tracker as of the 2026-10-02 retrieval.",
            ],
            sources=[
                _src(1, "original_release", "https://texaspublicopinionresearch.substack.com/p/new-poll-in-texas-general-election-662", "Texas Public Opinion Research", "2026-09-25", True, "Primary narrative release."),
            ],
            methodology="Not published in the narrative beyond likely voters, dates, sample size, margin of error, and the leaner note.",
            subgroups=_pair(
                ["Independents"],
                [37],
                [52],
                "party",
                "TPOR September release. Undecided among this group is 5. Leaner treatment of party identification is not defined in the article. Subgroup n not reported.",
            ),
            notes="Among independents the release also reports 5 percent undecided. That cell is not a third candidate share on the statewide topline.",
        ),
        _poll(
            external_key="marist-2026-09",
            pollster="Marist Poll",
            canonical="Marist Poll",
            parent="Marist University",
            sponsor="NPR/Marist",
            sponsor_type="media",
            release="2026-09-23",
            start="2026-09-17",
            end="2026-09-20",
            n=1139,
            n_note="Stated by Marist.",
            sample_type="RV",
            mode=["live telephone", "text-to-web", "online panel"],
            moe=4.4,
            moe_kind="sampling_error",
            ballot="two_candidate_remainder_unpublished",
            flags=["undecided_permitted"],
            wording=None,
            population="Texas registered voters 18 and older.",
            approved=True,
            confidence=0.78,
            results=[
                ("Greg Abbott", "Republican", 46, "candidate"),
                ("Gina Hinojosa", "Democrat", 49, "candidate"),
            ],
            warnings=[
                "Marist's narrative gives Hinojosa 49 and Abbott 46 and does not publish the remainder. 46+49=95. The TPP tracker says Other 1 and Undecided 3, which sums with the candidates to 99. Those remainder figures are NOT stored as results because they are aggregator-only.",
                "Independents: the narrative says Hinojosa receives 52 percent and does not give Abbott's share. That incomplete cell is not stored as a crosstab.",
            ],
            sources=[
                _src(1, "original_release", "https://maristpoll.marist.edu/polls/2026-midterm-elections-in-texas-september-2026/", "Marist Poll", "2026-09-23", True, "Primary narrative. Full table packet was linked from the page and not separately archived in this import."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Remainder categories differ from what the narrative states."),
            ],
            methodology="Multi-mode: live phone interviewers, text, or online. Registered voters. MOE ±4.4 for n=1,139.",
        ),
        _poll(
            external_key="emerson-2026-09",
            pollster="Emerson College Polling",
            canonical="Emerson College Polling",
            sponsor="Nexstar Media",
            sponsor_type="media",
            release="2026-09-17",
            start="2026-09-12",
            end="2026-09-14",
            n=1000,
            n_note="Stated by Emerson.",
            sample_type="LV",
            mode=["text-to-web", "online panel"],
            moe=3.0,
            moe_kind="credibility_interval",
            ballot="three_candidate_undecided_permitted",
            flags=["three_candidate", "undecided_permitted"],
            wording=None,
            population="Texas likely voters.",
            weighting="Gender, education, race, age, and region, using Census parameters and a voter file.",
            approved=True,
            confidence=0.86,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 46, "candidate"),
                ("Pat Dixon", "Libertarian", 2, "candidate"),
                ("Undecided", None, 4, "undecided"),
            ],
            warnings=[
                "Shares sum to 101. Emerson's credibility interval is treated as the uncertainty input, not a classical simple-random-sample margin of error.",
            ],
            sources=[
                _src(1, "original_release", "https://emersoncollegepolling.com/texas-2026-poll-talarico-and-paxton-in-dead-heat-abbott-maintains-edge/", "Emerson College Polling", "2026-09-17", True, "Primary release."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Agrees on 49 / 46 / Dixon 2 / undecided 4."),
            ],
            methodology="Probability-based panel from Consensus Strategies via MMS text-to-web, plus PureSpectrum panel interviews. Hosted on QuestionPro. Sponsor: Nexstar Media.",
            panel="Consensus Strategies; PureSpectrum",
        ),
        _poll(
            external_key="reconmr-2026-09",
            pollster="ReconMR",
            canonical="ReconMR",
            sponsor=None,
            sponsor_type="unknown",
            release="2026-09-17",
            start="2026-09-08",
            end="2026-09-11",
            n=614,
            n_note="Sample size 614 and MOE ±4.3 are corroborated by the Texas Politics Project tracker and several news writeups. They were not extracted from the ReconMR PDF bytes in this import because the PDF URL returned HTTP 403. Treat N and MOE as aggregator-corroborated, not as PDF-extracted.",
            sample_type="LV",
            mode=["unknown"],
            moe=4.3,
            moe_kind="sampling_error",
            ballot="two_candidate_plus_someone_else",
            flags=["undecided_permitted", "someone_else_option"],
            wording="If the election for Governor of Texas was held today, who would you vote for if the candidates were the Republican, Greg Abbott, the Democrat, Gina Hinojosa, or someone else? (Names were rotated.)",
            population="Likely Texas voters.",
            approved=True,
            confidence=0.62,
            results=[
                ("Greg Abbott", "Republican", 45, "candidate"),
                ("Gina Hinojosa", "Democrat", 49, "candidate"),
                ("No vote", None, 3, "would_not_vote"),
                ("No opinion", None, 4, "undecided"),
            ],
            warnings=[
                "Trend table in the ReconMR September release, as quoted from the PDF text, is Abbott 45, Hinojosa 49, no vote 3, no opinion 4. Those four numbers sum to 101.",
                "The TPP tracker splits the non-candidate remainder into Dixon 0, someone else 2, wouldn't vote 1, and DK 4. That split is not stored as separate results because this import did not read it off a saved PDF.",
                "270toWin labels this 614-interview survey 'Siena College'. Political.org labels it 'Siena Research Institute/ReconMR'. The San Antonio Current pairs ReconMR with Siena. The document URL is a ReconMR PDF. Those labels are treated as aliases of this one survey, not as additional polls. The June NYT/Siena survey is a different poll.",
                "Sponsor is blank because the September document's sponsor was not confirmed.",
            ],
            sources=[
                _src(1, "original_pdf", "https://reconmr.com/wp-content/uploads/2026/09/ReconMR-Texas-Poll-September-Release-Final.pdf", "ReconMR", "2026-09-17", True, "Primary PDF URL. Local download was blocked with HTTP 403 on 2026-10-02."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Calls the pollster Recon MR."),
                _src(4, "news", "https://www.sacurrent.com/news/realclearpolitics-moves-texas-governors-race-to-a-tossup-six-weeks-out-from-election-day/", "San Antonio Current", "2026-09-21", False, "Attributes the 49–45 result to ReconMR and Siena and gives n=614, field Sept 8–11."),
                _src(3, "aggregator", "https://www.270towin.com/2026-governor-polls/texas", "270toWin", None, False, "Lists the same 614 LV, 49–45 result under Siena College with a Sept 17 release."),
            ],
            methodology="Not fully archived locally. See the PDF URL.",
            duplicate_aliases=["Siena College September 2026 614 LV", "Siena/ReconMR September 2026"],
        ),
        _poll(
            external_key="univision-yougov-2026-09",
            pollster="YouGov",
            canonical="YouGov / N+ Univision",
            parent="YouGov",
            sponsor="N+ Univision / TelevisaUnivision",
            sponsor_type="media",
            release="2026-09-09",
            start="2026-08-27",
            end="2026-09-04",
            n=1000,
            n_note="Stated in the TelevisaUnivision release. Hispanic oversample of 564 was weighted down in the statewide estimates.",
            sample_type="RV",
            mode=["online panel"],
            moe=3.6,
            moe_kind="equivalent_nonprobability",
            ballot="two_candidate_undecided_permitted",
            flags=["undecided_permitted"],
            population="Texas registered voters, interviewed online by YouGov.",
            weighting="Gender, age, race and ethnicity, education, region, and presidential vote, using registration lists, ACS, CPS, and an approximate 2024 vote.",
            approved=True,
            confidence=0.8,
            results=[
                ("Greg Abbott", "Republican", 47, "candidate"),
                ("Gina Hinojosa", "Democrat", 47, "candidate"),
                ("Undecided", None, 5, "undecided"),
            ],
            warnings=[
                "The press release says this is not a probability sample. ±3.6 is an equivalent margin of error for a matched propensity-score design, not a classical MOE.",
                "47+47+5=99. TPP adds Other 1 percent. That 1 point is not stored as a result because the press-release paragraph does not itemize it.",
                "270toWin calls the sample LV. The TelevisaUnivision release and the TPP tracker say registered voters. Registered voters are used.",
                "TPP names the poll Televisa/Univision. The release says YouGov conducted it for N+ Univision. Same survey.",
            ],
            sources=[
                _src(2, "sponsor_release", "https://corporate.televisaunivision.com/press/2026/09/09/n-univision-news-poll-finds-texas-governors-and-senate-races-deadlocked-ahead-of-2026-midterms/", "TelevisaUnivision", "2026-09-09", True, "Sponsor release with fieldwork description."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Agrees on 47–47 and RV. Adds an other category not used here."),
            ],
            methodology="YouGov online sample. Dr. Sergio García-Ríos oversaw the survey for N+ Univision. Equivalent MOE for the Hispanic oversample is ±5.0 and is not the statewide figure.",
            panel="YouGov",
        ),
        _poll(
            external_key="emerson-2026-08",
            pollster="Emerson College Polling",
            canonical="Emerson College Polling",
            sponsor="Nexstar Media",
            sponsor_type="media",
            release="2026-08-13",
            start="2026-08-09",
            end="2026-08-10",
            n=1000,
            n_note="Stated by Emerson.",
            sample_type="LV",
            mode=["text-to-web", "online panel"],
            moe=3.0,
            moe_kind="credibility_interval",
            ballot="two_candidate_undecided_permitted",
            flags=["undecided_permitted"],
            population="Texas likely voters.",
            weighting="Gender, education, race, age, and region.",
            approved=True,
            confidence=0.8,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 45, "candidate"),
                ("Undecided", None, 4, "undecided"),
            ],
            warnings=[
                "Emerson's governor paragraph states 49, 45, and 4 percent undecided (sum 98) and does not mention a third named candidate. TPP adds someone else 3, which would push the sum to 101. The someone-else figure is not stored.",
                "The September Emerson release says Hinojosa moved from 45 to 46 and Abbott stayed at 49, which matches this paragraph.",
            ],
            sources=[
                _src(1, "original_release", "https://emersoncollegepolling.com/texas-2026-poll-paxton-and-talarico/", "Emerson College Polling", "2026-08-13", True, "Primary release."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Adds someone else 3, which conflicts with the release paragraph."),
            ],
            methodology="Same general Emerson/Nexstar design as September: Consensus Strategies text-to-web plus PureSpectrum. Credibility interval ±3.",
            panel="Consensus Strategies; PureSpectrum",
        ),
        _poll(
            external_key="ut-tpp-2026-08",
            pollster="University of Texas / Texas Politics Project",
            canonical="University of Texas / Texas Politics Project",
            parent="University of Texas at Austin",
            sponsor="Texas Politics Project",
            sponsor_type="university",
            release="2026-08-24",
            start="2026-08-05",
            end="2026-08-13",
            n=1200,
            n_note="Stated in the UT/Texas Politics Project release.",
            sample_type="RV",
            mode=["online panel"],
            moe=2.83,
            design_moe=3.58,
            moe_kind="sampling_error",
            ballot="multi_candidate_undecided_permitted",
            flags=["three_candidate", "undecided_permitted", "someone_else_option"],
            wording="The release's trial-ballot paragraph includes Abbott, Hinojosa, Pat Dixon, someone else, and no opinion. A separate dataset page titles a governor item as Abbott and Hinojosa only. Both wordings are preserved; the numeric ballot used here is the one in the release narrative.",
            population="Registered voters in Texas.",
            approved=True,
            confidence=0.84,
            results=[
                ("Greg Abbott", "Republican", 45, "candidate"),
                ("Gina Hinojosa", "Democrat", 40, "candidate"),
                ("Pat Dixon", "Libertarian", 3, "candidate"),
                ("Someone else", None, 2, "other"),
                ("No opinion", None, 10, "undecided"),
            ],
            warnings=[
                "The release prints two uncertainty figures: ±2.83, and ±3.58 when accounting for the weighted sample. The model uses 3.58 when design-effect MOEs are preferred. Both numbers are stored.",
                "The same release once refers to 'Libertarian Ted Dixon' in a party crosstab sentence and to Pat Dixon in the topline. The topline name Pat Dixon is stored. The conflicting sentence is not treated as a different candidate.",
                "Party crosstab sentences are incomplete (they do not give both candidates in each party) and are not stored as subgroup shares, except where both candidates are stated.",
            ],
            sources=[
                _src(1, "original_release", "https://texaspolitics.utexas.edu/blog/new-ut-texas-politics-project-poll-finds-talarico-leading-paxton-abbott-leading-hinojosa-continued-resistance-to-data-centers-2", "Texas Politics Project", "2026-08-24", True, "Pollster narrative with dates, n, both MOEs, and the 45/40/3/2/10 ballot."),
                _src(1, "methodology", "https://texaspolitics.utexas.edu/set/gubernatorial-trial-ballot-august-2026", "Texas Politics Project", None, False, "Dataset page whose question text names only Abbott and Hinojosa. See the wording warning."),
            ],
            methodology="YouGov internet sample of 1,200 registered voters, August 5–13, 2026. Margin of error ±2.83 (3.58 with the weighted sample).",
            panel="YouGov",
            subgroups=_pair(
                ["Suburban"],
                [40],
                [44],
                "urbanicity",
                "August UT/TPP narrative states Hinojosa 44, Abbott 40 in the suburbs, and an approximate suburban margin of error of 3.88 points. Subgroup n was not reported. The urban 44–43 / 45–43 parenthetical does not say which candidate is which, so it is not stored.",
            ),
        ),
        _poll(
            external_key="bush-reconmr-2026-07",
            pollster="ReconMR",
            canonical="ReconMR",
            parent="ReconMR",
            sponsor="Texas A&M Bush School",
            sponsor_type="university",
            release="2026-08-07",
            start="2026-07-27",
            end="2026-07-30",
            n=619,
            n_note="Crosstab PDF: 619 likely voters. 455 live telephone and 164 text-to-web.",
            sample_type="LV",
            mode=["live telephone", "text-to-web"],
            moe=4.7,
            moe_kind="sampling_error",
            ballot="multi_candidate_undecided_permitted",
            flags=["three_candidate", "undecided_permitted", "someone_else_option"],
            wording="If the election for Governor of Texas was held today, who would you vote for if the candidates were the Republican, Greg Abbott, the Democrat, Gina Hinojosa, or someone else? Names were rotated. The crosstab still prints a Pat Dixon column.",
            population="Likely Texas voters.",
            weighting="The release says the ±4.7 margin of error includes design effects from weighting.",
            approved=True,
            confidence=0.9,
            results=[
                ("Greg Abbott", "Republican", 46, "candidate"),
                ("Gina Hinojosa", "Democrat", 45, "candidate"),
                ("Someone else", None, 3, "other"),
                ("Pat Dixon", "Libertarian", 0, "candidate"),
                ("Wouldn't vote", None, 1, "would_not_vote"),
                ("Don't know/Refused", None, 5, "undecided"),
            ],
            warnings=[
                "The crosstab headline window is July 27–30. A methodology sentence in the same document says the survey was fielded between July 26 and July 30. The stored field dates follow the headline window. July 26 is not silently substituted.",
                "The same document says the overall MOE is ±4.7 including design effects, and also says 'For full surveys, the margin of error is ±5.5.' The 5.5 sentence is ambiguous and is not used.",
                "TPP collapses Dixon and someone else/DK into a remainder. The crosstab breakdown is used instead.",
            ],
            sources=[
                _src(1, "crosstab", "https://reconmr.com/wp-content/uploads/2026/08/TXP002-Texas-Pulse-Texas-AM-Bush-School-Crosstabs.pdf", "ReconMR", None, True, "Crosstab PDF with topline and subgroup percentages."),
                _src(1, "original_pdf", "https://static.politico.com/50/49/6b5b032a473f98ebce8b8c7d7940/texas-pulse-august-release-august-7-2026-final.pdf", "Texas Pulse", "2026-08-07", False, "Release memo. Governor trend table matches 46–45."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Discovery index. Remainder is collapsed."),
            ],
            methodology="Dual-frame live telephone (English and Spanish) plus text-to-web. Sample from the L2 registered-voter database. No incentives. Panel completes: 0.",
            subgroups=bush_subgroups,
        ),
        _poll(
            external_key="fox-2026-07",
            pollster="Fox News (Beacon Research / Shaw & Company Research)",
            canonical="Fox News",
            parent="Fox News",
            sponsor="Fox News",
            sponsor_type="media",
            release="2026-07-30",
            start="2026-07-23",
            end="2026-07-27",
            n=1006,
            n_note="Extracted from the Fox topline PDF saved locally on 2026-10-02.",
            sample_type="RV",
            mode=["live telephone", "text-to-web"],
            moe=3.0,
            moe_kind="sampling_error",
            ballot="two_candidate_leaners_pushed",
            flags=["leaners_pushed", "undecided_permitted"],
            wording="If the Texas election for governor were today, would you vote for: [IF DON'T KNOW: Do you lean closer to one candidate?] [ROTATE NAMES]",
            population="Texas registered voters drawn from a statewide voter file.",
            weighting="Age, race, education, and area when necessary.",
            approved=True,
            confidence=0.93,
            results=[
                ("Greg Abbott", "Republican", 50, "candidate"),
                ("Gina Hinojosa", "Democrat", 49, "candidate"),
                ("Other", None, None, "other"),
                ("Wouldn't vote", None, None, "would_not_vote"),
                ("Don't know", None, None, "undecided"),
            ],
            symbol_map={"Other": "*", "Wouldn't vote": "-", "Don't know": "*"},
            warnings=[
                "Fox prints * for less than one-half of one percent and a dash for zero. Other and don't know are asterisks. Wouldn't vote is zero. Those symbols are stored as symbols, not converted into 0.4 or into the TPP figure.",
                "TPP says someone else/DK is 4. That conflicts with this topline (50 and 49 plus two asterisks). The PDF wins. The 4 is not used.",
                "A methodology sentence says phone numbers are representative of voters 'across the city.' The rest of the document is statewide. The sentence is preserved, not corrected.",
            ],
            sources=[
                _src(1, "original_pdf", "https://static.foxnews.com/foxnews.com/content/uploads/2026/07/fox_july-23-27-2026_texas_topline_july-30-release.pdf", "Fox News", "2026-07-30", True, "Local copy saved under polling/data/raw on 2026-10-02."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Conflicts on the remainder."),
            ],
            methodology="1,006 registered voters. Landline 72, cellphone 681, text-to-web 253. Hispanic oversample of 296 brings the Hispanic interview count to 556. That is a sample count, not a governor crosstab result. Braun Research fielded the telephone interviews. MOE ±3 on the full sample. Bilingual, English or Spanish.",
            local_note="polling/data/raw/2026/09/02/fox_july-23-27-2026_texas_topline_july-30-release.pdf",
        ),
        # --- Discovered, not approved for the model ---
        _poll(
            external_key="tsu-yougov-2026-09",
            pollster="Texas Southern University / YouGov",
            canonical="Texas Southern University / YouGov",
            sponsor="Texas Southern University",
            sponsor_type="university",
            release="2026-09-22",
            start="2026-09-15",
            end="2026-09-19",
            n=1800,
            n_note="Texas Politics Project tracker only in this import.",
            sample_type="LV",
            moe=2.31,
            ballot="three_candidate_undecided_permitted",
            approved=False,
            confidence=0.35,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 45, "candidate"),
                ("Pat Dixon", "Libertarian", 2, "candidate"),
                ("Unsure", None, 4, "undecided"),
            ],
            warnings=["Topline is from the TPP tracker only. No original TSU or YouGov release was archived in this import, so the poll is not in the model."],
            sources=[_src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, True, "Discovery index. Not a primary source.")],
        ),
        _poll(
            external_key="mason-dixon-2026-09",
            pollster="Mason-Dixon",
            canonical="Mason-Dixon",
            sponsor="NBC News / Telemundo",
            sponsor_type="media",
            release=None,
            start=None,
            end=None,
            n=625,
            n_note="Sample size 625 appears in more than one secondary source. Dates and sample type do not agree.",
            sample_type="Other",
            moe=4.0,
            ballot="unresolved",
            approved=False,
            confidence=0.2,
            results=[
                ("Greg Abbott", "Republican", 48, "candidate"),
                ("Gina Hinojosa", "Democrat", 41, "candidate"),
            ],
            warnings=[
                "Not approved. TPP says NBC/Mason-Dixon, field Sept 9–10, LV, other/undecided 11. Political.org says Telemundo, field Sept 8–10, released Sept 15, Abbott 48, Hinojosa 41, Raphoon 2, Dixon 1, undecided 8. Ballotpedia's Mason-Dixon row in this window is a Senate result and is not used. Dates, sponsor, sample type, and the remainder are unresolved, so no field dates are stored.",
            ],
            sources=[
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "One version of the dates and the collapsed remainder."),
                _src(4, "news", "https://political.org/2026-governor-elections/", "Political.org", None, False, "A different date window and a named third-candidate split that was not confirmed on a Mason-Dixon document."),
            ],
        ),
        _poll(
            external_key="aarp-2026-09",
            pollster="Fabrizio Ward / Impact Research",
            canonical="AARP Texas / Fabrizio Ward / Impact Research",
            sponsor="AARP Texas",
            sponsor_type="pac_advocacy",
            release="2026-09-10",
            start="2026-08-30",
            end="2026-09-01",
            n=895,
            n_note="Secondary sources agree on 895 likely voters. The MOE does not.",
            sample_type="LV",
            moe=None,
            ballot="two_candidate_undecided_permitted",
            approved=False,
            confidence=0.3,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 46, "candidate"),
                ("Undecided", None, 5, "undecided"),
            ],
            warnings=[
                "Not approved. TPP prints MOE ±3.0 and other 0. Political.org and 270toWin print ±3.3. No AARP topline PDF was archived here, so the MOE is left blank rather than choosing one.",
                "Political.org says Abbott leads 59–38 among voters 50 and older. That is a partial subgroup from a secondary source and is not stored as a crosstab.",
            ],
            sources=[
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "MOE ±3.0."),
                _src(4, "news", "https://political.org/2026-governor-elections/", "Political.org", None, False, "MOE ±3.3 and the 50+ split."),
            ],
        ),
        _poll(
            external_key="tsu-yougov-2026-07",
            pollster="Texas Southern University / YouGov",
            canonical="Texas Southern University / YouGov",
            sponsor="Texas Southern University",
            sponsor_type="university",
            release=None,
            start="2026-07-27",
            end="2026-07-30",
            n=1200,
            sample_type="LV",
            moe=2.8,
            ballot="three_candidate_undecided_permitted",
            approved=False,
            confidence=0.3,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 43, "candidate"),
                ("Pat Dixon", "Libertarian", 3, "candidate"),
            ],
            warnings=["TPP tracker only. Someone else/DK is given as a combined 5 and is not split. Not in the model."],
            sources=[_src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, True, "Discovery index.")],
        ),
        _poll(
            external_key="nyt-siena-2026-06",
            pollster="New York Times / Siena College",
            canonical="New York Times / Siena",
            sponsor="New York Times",
            sponsor_type="media",
            release=None,
            start="2026-06-19",
            end="2026-06-27",
            n=656,
            sample_type="LV",
            moe=4.5,
            ballot="two_candidate_remainder_combined",
            approved=False,
            confidence=0.3,
            results=[
                ("Greg Abbott", "Republican", 51, "candidate"),
                ("Gina Hinojosa", "Democrat", 44, "candidate"),
            ],
            warnings=[
                "TPP tracker only in this import: someone else/DK combined at 5, not split. Not the September ReconMR survey that some aggregators mislabel as Siena.",
            ],
            sources=[_src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, True, "Discovery index.")],
        ),
        _poll(
            external_key="ut-tpp-2026-06",
            pollster="University of Texas / Texas Politics Project",
            canonical="University of Texas / Texas Politics Project",
            sponsor="Texas Politics Project",
            sponsor_type="university",
            release=None,
            start="2026-06-05",
            end="2026-06-12",
            n=1200,
            sample_type="RV",
            moe=2.83,
            ballot="unresolved",
            approved=False,
            confidence=0.4,
            results=[
                ("Greg Abbott", "Republican", 47, "candidate"),
                ("Gina Hinojosa", "Democrat", 40, "candidate"),
            ],
            warnings=[
                "Statewide 47–40, Dixon 2, and someone else/DK 12 are from the TPP tracker, not from a June release archived here. Not in the model.",
                "The August UT release does state June subgroup results. Those are stored. They are not a statewide topline.",
            ],
            sources=[
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "Statewide topline."),
                _src(1, "original_release", "https://texaspolitics.utexas.edu/blog/new-ut-texas-politics-project-poll-finds-talarico-leading-paxton-abbott-leading-hinojosa-continued-resistance-to-data-centers-2", "Texas Politics Project", "2026-08-24", True, "August release retrospectively stating June urban and suburban shares."),
            ],
            subgroups=_pair(
                ["Suburban"],
                [46],
                [41],
                "urbanicity",
                "June suburban shares as stated in the August 24 UT/TPP release: Abbott 46, Hinojosa 41. The urban parenthetical was not assigned to a candidate. Subgroup n not reported.",
            ),
        ),
        _poll(
            external_key="reconmr-2026-06",
            pollster="ReconMR",
            canonical="ReconMR",
            sponsor="Texas A&M Bush School",
            sponsor_type="university",
            release=None,
            start="2026-06-01",
            end="2026-06-04",
            n=807,
            n_note="N, MOE, and dates are from the TPP tracker. The July Texas Pulse memo confirms the June shares.",
            sample_type="LV",
            moe=4.0,
            ballot="two_candidate_plus_someone_else",
            approved=False,
            confidence=0.45,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 43, "candidate"),
                ("No vote", None, 3, "would_not_vote"),
                ("No opinion", None, 5, "undecided"),
            ],
            warnings=[
                "The July 2026 Texas Pulse trend table, in the August 7 memo, prints June as Abbott 49, Hinojosa 43, no vote 3, no opinion 5. N=807, MOE ±4.0, and the June 1–4 window were not in that trend line; they come from TPP. Held out of the model until a June primary document confirms N.",
            ],
            sources=[
                _src(1, "original_pdf", "https://static.politico.com/50/49/6b5b032a473f98ebce8b8c7d7940/texas-pulse-august-release-august-7-2026-final.pdf", "Texas Pulse", "2026-08-07", True, "Later memo confirming June shares."),
                _src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, False, "N, MOE, and dates."),
            ],
        ),
        _poll(
            external_key="quantus-2026-06",
            pollster="Quantus Insights",
            canonical="Quantus Insights",
            sponsor=None,
            sponsor_type="unknown",
            release=None,
            start="2026-06-03",
            end="2026-06-04",
            n=800,
            sample_type="LV",
            moe=3.5,
            ballot="two_candidate_undecided_permitted",
            approved=False,
            confidence=0.25,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 41, "candidate"),
                ("Don't know", None, 8, "undecided"),
            ],
            warnings=["TPP tracker only. 49+41+8=98. Not in the model. Some directories tag Quantus as Republican-aligned; that tag is not treated as established here."],
            sources=[_src(3, "aggregator", "https://texaspolitics.utexas.edu/blog/texas-2026-gubernatorial-poll-tracker", "Texas Politics Project", None, True, "Discovery index.")],
        ),
        _poll(
            external_key="tpor-2026-08",
            pollster="Texas Public Opinion Research",
            canonical="Texas Public Opinion Research",
            sponsor="Texas Public Opinion Research",
            sponsor_type="nonpartisan_public",
            release="2026-08-27",
            start=None,
            end=None,
            n=1000,
            sample_type="LV",
            moe=3.3,
            ballot="three_candidate_undecided_permitted",
            approved=False,
            confidence=0.28,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 42, "candidate"),
                ("Pat Dixon", "Libertarian", 1, "candidate"),
                ("Undecided", None, 6, "undecided"),
            ],
            warnings=[
                "Not approved. The September TPOR article says the August lead was +7, Dixon was 1, and undecided was 6. It does not print the August Abbott and Hinojosa levels. 49 and 42, n=1,000, MOE ±3.3, and the August 27 date are from 270toWin. 49+42+1+6=98. Field dates were not found. Held out.",
            ],
            sources=[
                _src(1, "original_release", "https://texaspublicopinionresearch.substack.com/p/new-poll-in-texas-general-election-662", "Texas Public Opinion Research", "2026-09-25", False, "Retrospective margin, Dixon, and undecided only."),
                _src(3, "aggregator", "https://www.270towin.com/2026-governor-polls/texas", "270toWin", None, False, "Levels, n, MOE, and a single date."),
            ],
        ),
        _poll(
            external_key="overton-2026-08",
            pollster="Overton Insights",
            canonical="Overton Insights",
            sponsor="Texas Public Policy Foundation",
            sponsor_type="pac_advocacy",
            release="2026-09-02",
            start="2026-08-24",
            end="2026-08-26",
            n=1167,
            sample_type="LV",
            moe=2.9,
            ballot="two_candidate_undecided_permitted",
            approved=False,
            confidence=0.22,
            results=[
                ("Greg Abbott", "Republican", 46.9, "candidate"),
                ("Gina Hinojosa", "Democrat", 45.8, "candidate"),
                ("Undecided", None, 7.3, "undecided"),
            ],
            warnings=["Political.org only in this import. Sponsor is described there as the Texas Public Policy Foundation. No original Overton release was archived. Not in the model. Tenths are kept as published by that secondary page and were not rounded."],
            sources=[_src(4, "news", "https://political.org/2026-governor-elections/", "Political.org", None, True, "Secondary compilation.")],
        ),
        _poll(
            external_key="socal-2026-09",
            pollster="SoCal Strategies",
            canonical="SoCal Strategies",
            sponsor=None,
            sponsor_type="unknown",
            release="2026-09-13",
            start="2026-09-12",
            end="2026-09-13",
            n=649,
            sample_type="LV",
            moe=None,
            ballot="two_candidate_remainder_unpublished",
            approved=False,
            confidence=0.15,
            results=[
                ("Greg Abbott", "Republican", 52, "candidate"),
                ("Gina Hinojosa", "Democrat", 44, "candidate"),
            ],
            warnings=["Political.org only. It says the margin of error was not published. A separate polling directory calls a similarly sized September poll partisan. Sponsorship is left unknown. Not in the model."],
            sources=[_src(4, "news", "https://political.org/2026-governor-elections/", "Political.org", None, True, "Secondary compilation.")],
        ),
        _poll(
            external_key="big-data-2026-09",
            pollster="Big Data Poll",
            canonical="Big Data Poll",
            sponsor=None,
            sponsor_type="unknown",
            release=None,
            start=None,
            end=None,
            n=698,
            sample_type="LV",
            moe=4.0,
            ballot="two_candidate_remainder_unpublished",
            approved=False,
            confidence=0.1,
            results=[
                ("Greg Abbott", "Republican", 49, "candidate"),
                ("Gina Hinojosa", "Democrat", 44, "candidate"),
            ],
            warnings=["PollingSource lists Big Data Poll, completed 2026-09-26, 698 LV, ±4, Hinojosa 44, Abbott 49. No field dates and no primary document were found in this import. Not in the model."],
            sources=[_src(3, "aggregator", "https://pollingsource.com/governors/TX", "PollingSource", None, True, "Aggregator row only.")],
        ),
    ]


def _src(tier, source_type, url, publisher, publication, primary, notes):
    return {
        "tier": tier,
        "source_type": source_type,
        "url": url,
        "publisher": publisher,
        "publication_date": publication,
        "is_primary": primary,
        "notes": notes,
    }


def _poll(**kwargs):
    results = []
    symbols = kwargs.pop("symbol_map", {})
    for candidate, party, pct, result_type in kwargs.pop("results"):
        results.append(
            {
                "candidate": candidate,
                "party": party,
                "percentage": pct,
                "reported_symbol": symbols.get(candidate),
                "result_type": result_type,
                "result_frame": "headline",
            }
        )
    record = {
        "external_key": kwargs["external_key"],
        "pollster": kwargs["pollster"],
        "pollster_canonical": kwargs["canonical"],
        "pollster_parent_company": kwargs.get("parent"),
        "sponsor": kwargs.get("sponsor"),
        "sponsor_type": kwargs.get("sponsor_type") or "unknown",
        "release_date": kwargs.get("release"),
        "field_start": kwargs.get("start"),
        "field_end": kwargs.get("end"),
        "sample_size": kwargs.get("n"),
        "sample_size_provenance": kwargs.get("n_note"),
        "sample_type": kwargs.get("sample_type"),
        "mode": kwargs.get("mode") or [],
        "reported_moe": kwargs.get("moe"),
        "design_effect_moe": kwargs.get("design_moe"),
        "moe_kind": kwargs.get("moe_kind"),
        "confidence_level": 0.95,
        "ballot_configuration": kwargs.get("ballot"),
        "ballot_flags": kwargs.get("flags") or [],
        "question_wording": kwargs.get("wording"),
        "population_description": kwargs.get("population"),
        "weighting_description": kwargs.get("weighting"),
        "state": "TX",
        "race": "Governor",
        "cycle": 2026,
        "approved_for_model": bool(kwargs.get("approved")),
        "auto_confidence": kwargs.get("confidence"),
        "results": results,
        "sources": kwargs.get("sources") or [],
        "methodology_text": kwargs.get("methodology"),
        "panel_provider": kwargs.get("panel"),
        "subgroups": kwargs.get("subgroups") or [],
        "extraction_warnings": kwargs.get("warnings") or [],
        "notes": kwargs.get("notes"),
        "alternate_frames": kwargs.get("alternate") or [],
        "duplicate_aliases": kwargs.get("duplicate_aliases") or [],
        "local_file_path": kwargs.get("local_note"),
    }
    return record
