import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import pg from "pg";
import { bindSql } from "./sql.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const schemaPath = path.join(__dirname, "..", "schema-postgres.sql");

let pool;
let dbWrapper;

function createStatement(client, sql) {
  return {
    async get(...args) {
      const { sql: pgSql, values } = bindSql(sql, args);
      const result = await client.query(pgSql, values);
      return result.rows[0];
    },
    async all(...args) {
      const { sql: pgSql, values } = bindSql(sql, args);
      const result = await client.query(pgSql, values);
      return result.rows;
    },
    async run(...args) {
      const { sql: pgSql, values } = bindSql(sql, args);
      const result = await client.query(pgSql, values);
      return {
        changes: result.rowCount ?? 0,
        lastInsertRowid: result.rows[0]?.id ?? null,
      };
    },
  };
}

function createDb(client, { pool: sharedPool } = {}) {
  let activeClient = client;

  const db = {
    prepare(sql) {
      return createStatement(activeClient, sql);
    },
    async exec(sql) {
      await activeClient.query(sql);
    },
    async query(sql, values = []) {
      return activeClient.query(sql, values);
    },
    transaction(fn) {
      return async (...args) => {
        const txClient = await sharedPool.connect();
        const prev = activeClient;
        activeClient = txClient;
        try {
          await txClient.query("BEGIN");
          const result = await fn(...args);
          await txClient.query("COMMIT");
          return result;
        } catch (err) {
          await txClient.query("ROLLBACK");
          throw err;
        } finally {
          activeClient = prev;
          txClient.release();
        }
      };
    },
  };

  return db;
}

export function getDatabaseUrl() {
  const url = process.env.DATABASE_URL?.trim();
  if (!url) {
    throw new Error("DATABASE_URL is required (PostgreSQL connection string)");
  }
  return url;
}

export async function initDb() {
  if (pool) return getDb();

  pool = new pg.Pool({
    connectionString: getDatabaseUrl(),
    ssl: process.env.DATABASE_SSL === "false" ? false : { rejectUnauthorized: false },
  });

  dbWrapper = createDb(pool, { pool });
  const schema = fs.readFileSync(schemaPath, "utf8");
  await pool.query(schema);
  await runMigrations(pool);
  return dbWrapper;
}

async function runMigrations(pool) {
  await pool.query(`
    ALTER TABLE offices
    ADD COLUMN IF NOT EXISTS up_for_reelection INTEGER NOT NULL DEFAULT 0
    CHECK (up_for_reelection IN (0, 1))
  `);
  await pool.query(`
    ALTER TABLE offices
    ADD COLUMN IF NOT EXISTS county_name TEXT
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS tga_staffers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      office_id INTEGER REFERENCES offices(id) ON DELETE SET NULL
    )
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS tga_staffer_offices (
      staffer_id INTEGER NOT NULL REFERENCES tga_staffers(id) ON DELETE CASCADE,
      office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
      PRIMARY KEY (staffer_id, office_id)
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_tga_staffer_offices_office ON tga_staffer_offices(office_id)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS tga_staffer_counties (
      staffer_id INTEGER NOT NULL REFERENCES tga_staffers(id) ON DELETE CASCADE,
      county_name TEXT NOT NULL,
      PRIMARY KEY (staffer_id, county_name)
    )
  `);
  await pool.query(`
    INSERT INTO tga_staffer_offices (staffer_id, office_id)
    SELECT id, office_id
    FROM tga_staffers
    WHERE office_id IS NOT NULL
    ON CONFLICT DO NOTHING
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS office_counties (
      office_id INTEGER NOT NULL REFERENCES offices(id) ON DELETE CASCADE,
      county_name TEXT NOT NULL,
      PRIMARY KEY (office_id, county_name)
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_office_counties_county ON office_counties(county_name)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS app_users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      display_name TEXT NOT NULL,
      role TEXT NOT NULL CHECK (role IN ('admin', 'viewer')) DEFAULT 'viewer',
      password_hash TEXT NOT NULL,
      active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_app_users_role ON app_users(role)
  `);
  await pool.query(`
    CREATE TABLE IF NOT EXISTS app_sessions (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES app_users(id) ON DELETE CASCADE,
      token_hash TEXT NOT NULL UNIQUE,
      expires_at TIMESTAMPTZ NOT NULL,
      remember_me INTEGER NOT NULL DEFAULT 0 CHECK (remember_me IN (0, 1)),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_app_sessions_user ON app_sessions(user_id)
  `);
  await pool.query(`
    CREATE INDEX IF NOT EXISTS idx_app_sessions_expires ON app_sessions(expires_at)
  `);
  await pool.query(`
    ALTER TABLE metric_contest_candidates
    ADD COLUMN IF NOT EXISTS contest_margin DOUBLE PRECISION
  `);
  await pool.query(`
    UPDATE county_election_results
    SET county_key = 'la_salle', county_name = 'La Salle'
    WHERE county_key = 'lasalle'
  `);
  await pool.query(`
    UPDATE county_election_results
    SET gop_pct = gop_pct / 100
    WHERE gop_pct IS NOT NULL AND ABS(gop_pct) > 1
  `);
  await pool.query(`
    UPDATE county_election_results
    SET dem_pct = dem_pct / 100
    WHERE dem_pct IS NOT NULL AND ABS(dem_pct) > 1
  `);
  await pool.query(`
    UPDATE county_election_results
    SET margin = margin / 100
    WHERE margin IS NOT NULL AND ABS(margin) > 1
  `);
}

export function getDb() {
  if (!dbWrapper) {
    throw new Error("Database not initialized — call initDb() before getDb()");
  }
  return dbWrapper;
}

export async function closeDb() {
  if (pool) {
    await pool.end();
    pool = undefined;
    dbWrapper = undefined;
  }
}
